services:
  - type: web
    name: caribbean-travel
    env: node
    plan: free
    buildCommand: npm install --prefix server
    startCommand: npm --prefix server start
    envVars:
      - key: RAPIDAPI_KEY
        sync: false
